### ISSUE TITLE
Can you update the Packagist repo?

### ISSUE THREAD

**Issue by simonhamp** [pelim/laravel-zmq#2]
It would be awesome if you could set this up to happen automatically :)

https://packagist.org/packages/pelim/laravel-zmq

Maybe I can do it if you add me as a maintainer there too?

**Comment by ryanwohara** [comment]
For anyone that needs to install v1 in the meantime, add this to composer.json:

```
    "repositories": [{
        "type": "git",
        "url": "https://github.com/pelim/laravel-zmq"
    }]
```

**Comment by simonhamp** [comment]
I just spotted that it's been updated. Thanks @pelim!
